### ISSUE TITLE
고정1)게임 소리 설정 버튼

### ISSUE THREAD

**Issue by ye1rm** [ye1rm/team1#39]

**Comment by JennyPark0204** [comment]
진행 중 클릭 하면 sound_status = not sound_status 로 소리상태를 반전 시켜 아이콘을 변경하는 것 까지 구현 완료 - 최예림

아직 sound 설정을 하지 않아서 bgm 설정 하고 테스트 할 필요 있어요. 진행중으로 옮겨주세요
